kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cmdb.fullname" . }}-cmdb-api
  labels:
    {{- include "cmdb.labels" . | nindent 4 }}
data:
  {{- include "cmdb.mysql.redis" . | nindent 2 -}}